### ISSUE TITLE
Cannot download from nexus

### ISSUE THREAD

**Issue by adrian-brown** [exactpro/sailfish-core#4] opened 2019-12-24 09:33 UTC
https://artifactory5.exp.exactpro.com/artifactory/

is unavailable.

**Comment by Nikita-Smirnov-Exactpro** [comment] 2019-12-24 11:17
Hi, adrian-brown

artifactory5.exp.exactpro.com is an internal repository. Gradle skips unavailable repositories and tries to use others declared in the build script. Please write the command which you are using to build and attach the console output to this issue.

**Comment by adrian-brown** [comment] 2019-12-24 13:48
Is that a failure?

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'sailfish'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jfrog.buildinfo:build-info-extractor-gradle:4.7.2.
     Required by:
         project :
      > Could not resolve org.jfrog.buildinfo:build-info-extractor-gradle:4.7.2.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/org/jfrog/buildinfo/build-info-extractor-gradle/4.7.2/build-info-extractor-gradle-4.7.2.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/org/jfrog/buildinfo/build-info-extractor-gradle/4.7.2/build-info-extractor-gradle-4.7.2.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve org.jfrog.buildinfo:build-info-extractor-gradle:4.7.2.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/org/jfrog/buildinfo/build-info-extractor-gradle/4.7.2/build-info-extractor-gradle-4.7.2.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/org/jfrog/buildinfo/build-info-extractor-gradle/4.7.2/build-info-extractor-gradle-4.7.2.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve org.jfrog.buildinfo:build-info-extractor-gradle:4.7.2.
         > Could not get resource 'https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle/4.7.2/build-info-extractor-gradle-4.7.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle/4.7.2/build-info-extractor-gradle-4.7.2.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.bmuschko:gradle-tomcat-plugin:2.5.
     Required by:
         project :
      > Could not resolve com.bmuschko:gradle-tomcat-plugin:2.5.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/bmuschko/gradle-tomcat-plugin/2.5/gradle-tomcat-plugin-2.5.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/bmuschko/gradle-tomcat-plugin/2.5/gradle-tomcat-plugin-2.5.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.bmuschko:gradle-tomcat-plugin:2.5.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/bmuschko/gradle-tomcat-plugin/2.5/gradle-tomcat-plugin-2.5.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/bmuschko/gradle-tomcat-plugin/2.5/gradle-tomcat-plugin-2.5.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.bmuschko:gradle-tomcat-plugin:2.5.
         > Could not get resource 'https://jcenter.bintray.com/com/bmuschko/gradle-tomcat-plugin/2.5/gradle-tomcat-plugin-2.5.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/bmuschko/gradle-tomcat-plugin/2.5/gradle-tomcat-plugin-2.5.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.github.onslip:gradle-one-jar:1.0.5.
     Required by:
         project :
      > Could not resolve com.github.onslip:gradle-one-jar:1.0.5.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/github/onslip/gradle-one-jar/1.0.5/gradle-one-jar-1.0.5.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/github/onslip/gradle-one-jar/1.0.5/gradle-one-jar-1.0.5.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.github.onslip:gradle-one-jar:1.0.5.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/github/onslip/gradle-one-jar/1.0.5/gradle-one-jar-1.0.5.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/github/onslip/gradle-one-jar/1.0.5/gradle-one-jar-1.0.5.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.github.onslip:gradle-one-jar:1.0.5.
         > Could not get resource 'https://jcenter.bintray.com/com/github/onslip/gradle-one-jar/1.0.5/gradle-one-jar-1.0.5.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/github/onslip/gradle-one-jar/1.0.5/gradle-one-jar-1.0.5.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve me.champeau.gradle:jmh-gradle-plugin:0.2.0.
     Required by:
         project :
      > Could not resolve me.champeau.gradle:jmh-gradle-plugin:0.2.0.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve me.champeau.gradle:jmh-gradle-plugin:0.2.0.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve me.champeau.gradle:jmh-gradle-plugin:0.2.0.
         > Could not get resource 'https://jcenter.bintray.com/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.exactpro.sailfish-gradle-plugin:sailfish-gradle-plugin:3.2.17.
     Required by:
         project :
      > Could not resolve com.exactpro.sailfish-gradle-plugin:sailfish-gradle-plugin:3.2.17.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/exactpro/sailfish-gradle-plugin/sailfish-gradle-plugin/3.2.17/sailfish-gradle-plugin-3.2.17.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/exactpro/sailfish-gradle-plugin/sailfish-gradle-plugin/3.2.17/sailfish-gradle-plugin-3.2.17.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.exactpro.sailfish-gradle-plugin:sailfish-gradle-plugin:3.2.17.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/exactpro/sailfish-gradle-plugin/sailfish-gradle-plugin/3.2.17/sailfish-gradle-plugin-3.2.17.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/exactpro/sailfish-gradle-plugin/sailfish-gradle-plugin/3.2.17/sailfish-gradle-plugin-3.2.17.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.exactpro.sailfish-gradle-plugin:sailfish-gradle-plugin:3.2.17.
         > Could not get resource 'https://jcenter.bintray.com/com/exactpro/sailfish-gradle-plugin/sailfish-gradle-plugin/3.2.17/sailfish-gradle-plugin-3.2.17.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/exactpro/sailfish-gradle-plugin/sailfish-gradle-plugin/3.2.17/sailfish-gradle-plugin-3.2.17.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve javax.xml.bind:jaxb-api:2.2.11.
     Required by:
         project :
      > Could not resolve javax.xml.bind:jaxb-api:2.2.11.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve javax.xml.bind:jaxb-api:2.2.11.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve javax.xml.bind:jaxb-api:2.2.11.
         > Could not get resource 'https://jcenter.bintray.com/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.github.ben-manes:gradle-versions-plugin:0.20.0.
     Required by:
         project :
      > Could not resolve com.github.ben-manes:gradle-versions-plugin:0.20.0.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/github/ben-manes/gradle-versions-plugin/0.20.0/gradle-versions-plugin-0.20.0.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/github/ben-manes/gradle-versions-plugin/0.20.0/gradle-versions-plugin-0.20.0.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.github.ben-manes:gradle-versions-plugin:0.20.0.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/github/ben-manes/gradle-versions-plugin/0.20.0/gradle-versions-plugin-0.20.0.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/github/ben-manes/gradle-versions-plugin/0.20.0/gradle-versions-plugin-0.20.0.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.github.ben-manes:gradle-versions-plugin:0.20.0.
         > Could not get resource 'https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/0.20.0/gradle-versions-plugin-0.20.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/0.20.0/gradle-versions-plugin-0.20.0.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve com.bmuschko:gradle-cargo-plugin:2.4.
     Required by:
         project :
      > Could not resolve com.bmuschko:gradle-cargo-plugin:2.4.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/bmuschko/gradle-cargo-plugin/2.4/gradle-cargo-plugin-2.4.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/com/bmuschko/gradle-cargo-plugin/2.4/gradle-cargo-plugin-2.4.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.bmuschko:gradle-cargo-plugin:2.4.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/bmuschko/gradle-cargo-plugin/2.4/gradle-cargo-plugin-2.4.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/com/bmuschko/gradle-cargo-plugin/2.4/gradle-cargo-plugin-2.4.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve com.bmuschko:gradle-cargo-plugin:2.4.
         > Could not get resource 'https://jcenter.bintray.com/com/bmuschko/gradle-cargo-plugin/2.4/gradle-cargo-plugin-2.4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/bmuschko/gradle-cargo-plugin/2.4/gradle-cargo-plugin-2.4.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-snapshot/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
         > Could not get resource 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
            > Could not HEAD 'http://artifactory5.exp.exactpro.com/artifactory/libs-release/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
               > artifactory5.exp.exactpro.com
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the 
```trustAnchors parameter must be non-empty

**Comment by bop0hz** [comment] 2019-12-25 09:58
Hi @adrian-brown, as we can see there is an issue with connectivity to jcenter public repository as well.

Could you please try to open the following links directly https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom
https://jcenter.bintray.com/me/champeau/gradle/jmh-gradle-plugin/0.2.0/jmh-gradle-plugin-0.2.0.pom

**Comment by bop0hz** [comment] 2020-01-14 16:55
Hi @adrian-brown,

is the issue is still relevant or we can close it?

**Closed** 2020-01-15 08:34 UTC
